---
title: "CPUC Predicting Mobile Broadband"
author: "Jose Mijangos"
date: "August 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("C:\\Users\\josem\\Desktop\\geo.R")
library(automap)
library(e1071)
```

## Functions
```{r}
# Returns average and reduces NA values
vector_avg = function(x1, x2) {
  x = apply(data.frame(x1,x2), 1, function(x) mean(na.omit(x)))
  x[is.nan(x)] = NA
  return(x)
}

# returns distance to k nearest tower
nearest_tower = function(tr_dat, te_dat, features, m) {
  matrix = distances_between(tr_dat[features], te_dat[features])
  distances = c(m)
  for(j  in 1:nrow(te_dat)){
    distance = c()
    for(n in m){
      i = order(matrix[j])[n]
      distance = c(distance, distm(c(tr_dat[i,features[1]], tr_dat[i,features[2]]), c(te_dat[j,features[1]], te_dat[j,features[2]]), fun = distHaversine)[,1] / 1609)
    }
    distances = rbind(distances, distance)
  }
  rownames(distances)=1:nrow(distances)-1
  distances = as.data.frame(distances[-1,])
  colnames(distances) = paste0("distance_", m)
  return(distances)
}

# returns tower density in a certain radius
tower_density = function(tr_dat, te_dat, features, m) {
  matrix = distances_between(tr_dat[features], te_dat[features])
  densities = c(m)
  for(j  in 1:nrow(te_dat)){
    density = c()
    for(n in m){
      density = c(density, sum(matrix[,j] < n))
    }
    densities = rbind(densities, density)
  }
  rownames(densities)=1:nrow(densities)-1
  densities = as.data.frame(densities[-1,])
  colnames(densities) = paste0("density_", m)
  return(densities)
}
```

## Read Data
```{r}
# Field Test Data
dat_raw = read.csv("C:\\Users\\josem\\Desktop\\Round12_Results_Final_20171120.csv")

# AT&T Tower Locations
att_towers = read.csv("C:\\Users\\josem\\Desktop\\att_towers.csv")
att_towers = att_towers[att_towers$State == "CA" | att_towers$State == "NV" | att_towers$State == "AZ" | att_towers$State == "OR",]
att_towers$NormalLONG = att_towers$Longitude
att_towers$NormalLAT = att_towers$Latitude

# T-Mobile Tower Locations
tmobile_towers = read.csv("C:\\Users\\josem\\Desktop\\tmobile_towers.csv")
tmobile_towers = tmobile_towers[tmobile_towers$state == " CA" | tmobile_towers$state == " NV" | tmobile_towers$state == " AZ" | tmobile_towers$state == " OR",]
tmobile_towers$NormalLONG = tmobile_towers$Longitude
tmobile_towers$NormalLAT = tmobile_towers$Latitude
```

## Preprocess Data
```{r collapse=TRUE, warning=FALSE, message=FALSE}
# Convert to Numeric
dat = as.data.frame(apply(dat_raw, 2, as.numeric))

# Restore Factors
dat$Provider = dat_raw$Provider
dat$Network = dat_raw$Network
dat$DeviceType = dat_raw$DeviceType
dat$Type = dat_raw$Type

# Aggregate TCP values
dat$wTCPUp   = vector_avg(dat$wTCPUp1, dat$wTCPUp2)
dat$wTCPDown = vector_avg(dat$wTCPDown1, dat$wTCPDown2)

# Remove tuples with bad lat/long values
dat = dat[dat$Longitude < -100,]

# Project Data
dat = dat[,c("LocationID", "Latitude", "Longitude", "NormalLONG", "NormalLAT", "Provider", "Network", "DeviceType", "Type", "SigStrength", "wMOS", "wTCPDown", "wTCPUp")]

# Remove all NAs
dat = na.omit(dat)

# Select data set for each Provider
dat_att = dat[dat$Provider == "AT&T" & dat$DeviceType=="Phone" & dat$Network=="LTE",]
dat_sprint = dat[dat$Provider == "Sprint" & dat$DeviceType=="Phone"& dat$Network=="LTE",]
dat_tmobile = dat[dat$Provider == "T-Mobile" & dat$DeviceType=="Phone" & dat$Network=="LTE",]
dat_verizon = dat[dat$Provider == "Verizon" & dat$DeviceType=="Phone" & dat$Network=="LTE",]
```

## Distance Matrix
```{r}
earth_radius_in_miles = 3959

n = nrow(dat_att)
locs = as.matrix(dat_att[1:n,c("NormalLONG", "NormalLAT")])
gdist = matrix(rep(NA, n*n), ncol=n)

for (i in 1:n) {
  temp = matrix(as.numeric(rep(locs[i,], each=n)), nrow=n)
  gdist[i,] = distHaversine(temp, locs, r=earth_radius_in_miles)  
}
```

## kNN Prediction Error
```{r}
Sig_knn_error = c()
wMOS_knn_error = c()
wTCPDown_knn_error = c()
wTCPUp_knn_error = c()

Sig_weighted_knn_error = c()
wMOS_weighted_knn_error = c()
wTCPDown_weighted_knn_error = c()
wTCPUp_weighted_knn_error = c()

for(l in 1:100) {
  Sig_knn_predictions = c()
  wMOS_knn_predictions = c()
  wTCPDown_knn_predictions = c()
  wTCPUp_knn_predictions = c()

  Sig_knn_weighted_predictions = c()
  wMOS_knn_weighted_predictions = c()
  wTCPDown_knn_weighted_predictions = c()
  wTCPUp_knn_weighted_predictions = c()
  for(i in 1:n) {
    kNearest = order(gdist[i,])[1:l+1]
    weights = 1/sort(gdist[i,][kNearest] + 0.001)
    weights = weights/sum(weights)
    
    Sig_knn_predictions = c(Sig_knn_predictions, mean(dat_att$SigStrength[kNearest]))
    wMOS_knn_predictions = c(wMOS_knn_predictions, mean(dat_att$wMOS[kNearest]))
    wTCPDown_knn_predictions = c(wTCPDown_knn_predictions, mean(dat_att$wTCPDown[kNearest]))
    wTCPUp_knn_predictions = c(wTCPUp_knn_predictions, mean(dat_att$wTCPUp[kNearest]))
    
    Sig_knn_weighted_predictions = c(Sig_knn_weighted_predictions, sum(weights * dat_att$SigStrength[kNearest]))
    wMOS_knn_weighted_predictions = c(wMOS_knn_weighted_predictions, sum(weights * dat_att$wMOS[kNearest]))
    wTCPDown_knn_weighted_predictions = c(wTCPDown_knn_weighted_predictions, sum(weights * dat_att$wTCPDown[kNearest]))
    wTCPUp_knn_weighted_predictions = c(wTCPUp_knn_weighted_predictions, sum(weights * dat_att$wTCPUp[kNearest]))
  }
  Sig_knn_error = c(Sig_knn_error, median(abs(Sig_knn_predictions - dat_att$SigStrength)))
  wMOS_knn_error = c(wMOS_knn_error, median(abs(wMOS_knn_predictions - dat_att$wMOS)))
  wTCPDown_knn_error = c(wTCPDown_knn_error, median(abs(wTCPDown_knn_predictions - dat_att$wTCPDown)/1000))
  wTCPUp_knn_error = c(wTCPUp_knn_error, median(abs(wTCPUp_knn_predictions - dat_att$wTCPUp)/1000))
  
  Sig_weighted_knn_error = c(Sig_weighted_knn_error, median(abs(Sig_knn_weighted_predictions - dat_att$SigStrength)))
  wMOS_weighted_knn_error = c(wMOS_weighted_knn_error, median(abs(wMOS_knn_weighted_predictions - dat_att$wMOS)))
  wTCPDown_weighted_knn_error = c(wTCPDown_weighted_knn_error, median(abs(wTCPDown_knn_weighted_predictions - dat_att$wTCPDown)/1000))
  wTCPUp_weighted_knn_error = c(wTCPUp_weighted_knn_error, median(abs(wTCPUp_knn_weighted_predictions - dat_att$wTCPUp)/1000))
}
```

## kNN Plots
```{r}
layout(matrix(c(1,2,3,4), 2, 2, byrow = TRUE))
plot(Sig_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 8.5), pch=19, ylab="absolute prediction error", main="Median SigStrength Error")
points(Sig_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
grid()

plot(wMOS_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 0.1), pch=19, ylab="absolute prediction error", main="Median wMOS Error")
points(wMOS_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
grid()

plot(wTCPDown_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 11), pch=19, ylab="absolute prediction error", main="Median wTCPDown Error")
points(wTCPDown_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown)))/1000, lty = 2, col = "red", lwd=3)
grid()

plot(wTCPUp_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 6.5), pch=19, ylab="absolute prediction error", main="Median wTCPUp Error")
points(wTCPUp_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp)))/1000, lty = 2, col = "red", lwd=3)
grid()
```

## Tower Model
```{r}
dat_tmobile = cbind(dat_tmobile, nearest_tower(tmobile_towers, dat_tmobile, c("NormalLONG","NormalLAT"), 1:10))
```

```{r}
fit_lm1_dist = lm(wTCPDown ~ distance_1, data=dat_att)
fit_lm2_dist = lm(wTCPDown ~ distance_1 + distance_2, data=dat_att)
fit_lm3_dist = lm(wTCPDown ~ distance_1 + distance_2 + distance_3, data=dat_att)
fit_lm4_dist = lm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4, data=dat_att)
fit_lm5_dist = lm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5, data=dat_att)
fit_lm6_dist = lm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6, data=dat_att)
fit_lm7_dist = lm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7, data=dat_att)
fit_lm8_dist = lm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8, data=dat_att)
fit_lm9_dist = lm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8 + distance_9, data=dat_att)
fit_lm10_dist = lm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8 + distance_9 + distance_10, data=dat_att)

fit_lm1_dens = lm(wTCPDown ~ density_0.1, data=dat_att)
fit_lm2_dens = lm(wTCPDown ~ density_0.1 + density_0.2, data=dat_att)
fit_lm3_dens = lm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3, data=dat_att)
fit_lm4_dens = lm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4, data=dat_att)
fit_lm5_dens = lm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5, data=dat_att)
fit_lm6_dens = lm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5 + density_0.6, data=dat_att)
fit_lm7_dens = lm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5 + density_0.6 + density_0.7, data=dat_att)
fit_lm8_dens = lm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5 + density_0.6 + density_0.7 + density_0.8, data=dat_att)
fit_lm9_dens = lm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5 + density_0.6 + density_0.7 + density_0.8 + density_0.9, data=dat_att)
fit_lm10_dens = lm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5 + density_0.6 + density_0.7 + density_0.8 + density_0.9 + density_1 , data=dat_att)

fit_glm1_dist = glm(wTCPDown/max(wTCPDown) ~ distance_1, data=dat_att, family = "binomial")
fit_glm2_dist = glm(wTCPDown/max(wTCPDown) ~ distance_1 + distance_2, data=dat_att, family = "binomial")
fit_glm3_dist = glm(wTCPDown/max(wTCPDown) ~ distance_1 + distance_2 + distance_3, data=dat_att, family = "binomial")
fit_glm4_dist = glm(wTCPDown/max(wTCPDown) ~ distance_1+distance_2+distance_3+distance_4, data=dat_att, family = "binomial")
fit_glm5_dist = glm(wTCPDown/max(wTCPDown) ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5, data=dat_att, family = "binomial")
fit_glm6_dist = glm(wTCPDown/wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6, data=dat_att, family = "binomial")
fit_glm7_dist = glm(wTCPDown/wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7, data=dat_att, family = "binomial")
fit_glm8_dist = glm(wTCPDown/wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8, data=dat_att, family = "binomial")
fit_glm9_dist = glm(wTCPDown/wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8 + distance_9, data=dat_att, family = "binomial")
fit_glm10_dist = glm(wTCPDown/wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8 + distance_9 + distance_10, data=dat_att, family = "binomial")

fit_glm1_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1, data=dat_att, family = "binomial")
fit_glm2_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2, data=dat_att, family = "binomial")
fit_glm3_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2+density_0.3, data=dat_att, family = "binomial")
fit_glm4_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2+density_0.3+density_0.4, data=dat_att, family = "binomial")
fit_glm5_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2+density_0.3+density_0.4+density_0.5, data=dat_att, family = "binomial")
fit_glm6_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2+density_0.3+density_0.4+density_0.5+density_0.6, data=dat_att, family = "binomial")
fit_glm7_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2+density_0.3+density_0.4+density_0.5+density_0.6+density_0.7, data=dat_att, family = "binomial")
fit_glm8_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2+density_0.3+density_0.4+density_0.5+density_0.6+density_0.7+density_0.8, data=dat_att, family = "binomial")
fit_glm9_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2+density_0.3+density_0.4+density_0.5+density_0.6+density_0.7+density_0.8+density_0.9, data=dat_att, family = "binomial")
fit_glm10_dens = glm(wTCPDown/max(wTCPDown) ~ density_0.1+density_0.2+density_0.3+density_0.4+density_0.5+density_0.6+density_0.7+density_0.8+density_0.9+density_1, data=dat_att, family = "binomial")

fit_svm1_dist = svm(wTCPDown ~ distance_1, data=dat_att)
fit_svm2_dist = svm(wTCPDown ~ distance_1 + distance_2, data=dat_att)
fit_svm3_dist = svm(wTCPDown ~ distance_1 + distance_2 + distance_3, data=dat_att)
fit_svm4_dist = svm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4, data=dat_att)
fit_svm5_dist = svm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5, data=dat_att)
fit_svm6_dist = svm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6, data=dat_att)
fit_svm7_dist = svm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7, data=dat_att)
fit_svm8_dist = svm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8, data=dat_att)
fit_svm9_dist = svm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8 + distance_9, data=dat_att)
fit_svm10_dist = svm(wTCPDown ~ distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8 + distance_9 + distance_10, data=dat_att)

fit_svm1_dens = svm(wTCPDown ~ density_0.1, data=dat_att)
fit_svm2_dens = svm(wTCPDown ~ density_0.1 + density_0.2, data=dat_att)
fit_svm3_dens = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3, data=dat_att)
fit_svm4_dens = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4, data=dat_att)
fit_svm5_dens = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5, data=dat_att)
fit_svm6_dens = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5+ density_0.6, data=dat_att)
fit_svm7_dens = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5 + density_0.6 + density_0.7, data=dat_att)
fit_svm8_dens = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5+ density_0.6 + density_0.7+ density_0.8, data=dat_att)
fit_svm9_dens = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5+ density_0.6 + density_0.7+ density_0.8+ density_0.9, data=dat_att)
fit_svm10_dens = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5+ density_0.6 + density_0.7+ density_0.8+ density_0.9+ density_1, data=dat_att)

fit_svm = svm(wTCPDown ~ density_0.1 + density_0.2 + density_0.3 + density_0.4 + density_0.5 + distance_1 + distance_2 + distance_3 + distance_4 + distance_5 + distance_6 + distance_7 + distance_8 + distance_9 + distance_10, data=dat_att)
```

```{r}
plot(c(
median(abs(dat_att$wTCPDown - predict(fit_lm1_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm2_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm3_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm4_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm5_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm6_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm7_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm8_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm9_dist)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm10_dist)))/1000
), ylab="absolute prediction error", type="b", lwd=3, pch=19,  col="blue", xlab="nearest tower", ylim=c(9,11))
points(c(
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm1_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm2_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm3_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm4_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm5_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm6_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm7_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm8_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm9_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm10_dist, type = "response")))/1000
), lwd=3, pch=19, col="green", type="b")
points(c(
median(abs(dat_att$wTCPDown - predict(fit_svm1_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm2_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm3_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm4_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm5_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm6_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm7_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm8_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm9_dist, type = "response")))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm10_dist, type = "response")))/1000
), lwd=3, pch=19, col="orange", type="b")
abline(h=min(wTCPDown_weighted_knn_error), lty=2, lwd=3)
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown)))/1000, lty = 2, col = "red", lwd=3)
```

```{r}
plot(c(
median(abs(dat_att$wTCPDown - predict(fit_lm1_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm2_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm3_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm4_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm5_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm6_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm7_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm8_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm9_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_lm10_dens)))/1000
) ~ seq(0.1,1,0.1), ylab="absolute prediction error", type="b", xlab="tower density", lwd=3, pch=19,  col="blue", ylim=c(9,10.5))
points(c(
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm1_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm2_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm3_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm4_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm5_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm6_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm7_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm8_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm9_dens, type = "response")))/1000,
median(abs(dat_att$wTCPDown - max(dat_att$wTCPDown)*predict(fit_glm10_dens, type = "response")))/1000
) ~ seq(0.1,1,0.1), lwd=3, pch=19, col="green", type="b")
points(c(
median(abs(dat_att$wTCPDown - predict(fit_svm1_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm2_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm3_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm4_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm5_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm6_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm7_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm8_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm9_dens)))/1000,
median(abs(dat_att$wTCPDown - predict(fit_svm10_dens)))/1000
) ~ seq(0.1,1,0.1), lwd=3, pch=19, col="orange", type="b")
abline(h=min(wTCPDown_weighted_knn_error), lty=2, lwd=3)
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown)))/1000, lty = 2, col = "red", lwd=3)
```

```{r}
barplot(c(median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown)))/1000, min(wTCPDown_knn_error), min(wTCPDown_weighted_knn_error), median(abs(dat_att$wTCPDown - predict(fit_svm)))/1000), col=c("red"), names.arg = c("Blind Prediction", "kNN", "Kriging", "Tower Model"), ylab="absolute prediction error")
```

## KNN plot vs SVM plot
```{r collapse=TRUE, warning=FALSE, message=FALSE}
ca=map_data('state', region='California')

ctrl = dat_att

xrang=seq(-124.5,-114,.05)
yrang=seq(32.5,42.25,.05 )
xtarg=c()
ytarg=c()

zhat_knn=matrix(0,length(xrang),length(yrang))
zhat_svm=matrix(0,length(xrang),length(yrang))

for(j in 1:length(yrang)){
  for(i in 1:length(xrang)){
    if(point.in.polygon(xrang[i], yrang[j], ca$long, ca$lat)){
      xtarg=c(xtarg, xrang[i])
      ytarg=c(ytarg, yrang[j])
    }
    else{
      xtarg=c(xtarg, NA)
      ytarg=c(ytarg, NA)
    }
  }
}

ztarg_knn = KNN(ctrl, data.frame(Longitude=xtarg[!is.na(xtarg)], Latitude=ytarg[!is.na(ytarg)], wDown=0), "wTCPDown", c("Latitude","Longitude"),7)

target_dat = data.frame(NormalLONG=xtarg[!is.na(xtarg)], NormalLAT=ytarg[!is.na(ytarg)])
target_dat = cbind(target_dat, nearest_tower(att_towers, target_dat, c("NormalLONG","NormalLAT"), 1:10))
target_dat = cbind(target_dat, tower_density(att_towers, target_dat, c("NormalLONG","NormalLAT"), seq(0.1,1,.1)))

ztarg_svm = predict(fit_svm, target_dat)

t=0
for(j in 1:length(yrang)){
  for(i in 1:length(xrang)){
    if(point.in.polygon(xrang[i], yrang[j], ca$long, ca$lat)){
      t=t+1
      zhat_knn[i,j]=mean(dat_att$wTCPDown)
      #zhat_svm[i,j]=ztarg_svm[t]
    }
    else{
      zhat_knn[i,j]=0
      #zhat_svm[i,j]=0

    }
  }
}
```

```{r}
layout(matrix(1:3,ncol=3), width = c(3,3,3),height = c(1,1))

ca=map_data('state', region='California')
plot(dat_att$NormalLAT ~ dat_att$NormalLONG, col=rainbow(80)[51:1][floor(dat_att$wTCPDown/max(dat_att$wTCPDown)*60)+1], pch=19, xlab="Longitude", ylab="Latitude", main="wTCPDown")
lines(ca, lwd=2)

image(xrang, yrang, zhat_knn, col=rainbow(50)[c(31,16)], xlab="Longitude", ylab="Latitude", main="kNN")
lines(ca, lwd=2)

image(xrang, yrang, zhat_svm, col=rainbow(50)[31:2], xlab="Longitude", ylab="Latitude", main="Tower Model")
lines(ca, lwd=2)

kriging_result$krige_output$var1.pred = kriging_result$krige_output$var1.pred * max(dat_att$wTCPDown)
plot(kriging_result$krige_output, col=rainbow(50)[31:2])
lines(ca, lwd=2)
```

```{r}
layout(matrix(1:2,ncol=2), width = c(3,3),height = c(1,1))

ca=map_data('state', region='California')
plot(dat_att$NormalLAT ~ dat_att$NormalLONG, col=rainbow(80)[51:1][floor(dat_att$wTCPDown/max(dat_att$wTCPDown)*60)+1], pch=19, xlab="Longitude", ylab="Latitude", main="wTCPDown")
lines(ca, lwd=2)

ca=map_data('state', region='California')
plot(dat_att$NormalLAT ~ dat_att$NormalLONG, col=rainbow(80)[51:1][floor(dat_att$wTCPUp/max(dat_att$wTCPUp)*30)+1], pch=19, xlab="Longitude", ylab="Latitude", main="wTCPUp")
lines(ca, lwd=2)
```

## Kriging Prediction Error
```{r collapse=TRUE, warning=FALSE, message=FALSE}
coordinates(dat_att) =~ NormalLONG + NormalLAT
Sig_kriging_error = c()
wMOS_kriging_error = c()
wTCPDown_kriging_error = c()
wTCPUp_kriging_error = c()

Sig_kriging_predictions = c()
wMOS_kriging_predictions = c()
wTCPDown_kriging_predictions = c()
wTCPUp_kriging_predictions = c()

for(i in 1:n){
  kriging_result = autoKrige(SigStrength/min(SigStrength)~1, dat_att[-i,], new_data = dat_att[i,])
  Sig_kriging_predictions = c(Sig_kriging_predictions, kriging_result$krige_output$var1.pred*min(dat_att[-i,]$SigStrength))
  
  kriging_result = autoKrige(wMOS/max(wMOS)~1, dat_att[-i,], new_data = dat_att[i,])
  wMOS_kriging_predictions = c(wMOS_kriging_predictions, kriging_result$krige_output$var1.pred*max(dat_att[-i,]$wMOS))
  
  kriging_result = autoKrige(wTCPDown/max(wTCPDown)~1, dat_att[-i,], new_data = dat_att[i,])
  wTCPDown_kriging_predictions = c(wTCPDown_kriging_predictions, kriging_result$krige_output$var1.pred*max(dat_att[-i,]$wTCPDown))
  
  kriging_result = autoKrige(wTCPUp/max(wTCPUp)~1, dat_att[-i,], new_data = dat_att[i,])
  wTCPUp_kriging_predictions = c(wTCPUp_kriging_predictions, kriging_result$krige_output$var1.pred*max(dat_att[-i,]$wTCPUp))
  
} 

Sig_kriging_error = median(abs(Sig_kriging_predictions - dat_att$SigStrength))
wMOS_kriging_error = median(abs(wMOS_kriging_predictions - dat_att$wMOS))
wTCPDown_kriging_error = median(abs(wTCPDown_kriging_predictions - dat_att$wTCPDown)/1000)
wTCPUp_kriging_error = median(abs(wTCPUp_kriging_predictions - dat_att$wTCPUp)/1000)
```

## Variograms
```{r collapse=TRUE, warning=FALSE, message=FALSE}
Sig_variogram = autofitVariogram(SigStrength/min(SigStrength)~1, dat_att, verbose=FALSE)
wMOS_variogram = autofitVariogram(wMOS/max(wMOS)~1,dat_att, verbose=FALSE)
wTCPDown_variogram = autofitVariogram(wTCPDown/max(wTCPDown)~1,dat_att, verbose=FALSE)
wTCPUp_variogram = autofitVariogram(wTCPUp/max(wTCPUp)~1,dat_att, verbose=FALSE)
```

## Variogram Plots
```{r}
layout(matrix(c(1,2,3,4), 2, 2, byrow = TRUE))
plot(Sig_variogram$exp_var$gamma~Sig_variogram$exp_var$dist, type="l", lwd=4, ylim=c(0,0.07), col="steelblue3", ylab="semi-varience", xlab="distance")
plot(wMOS_variogram$exp_var$gamma~Sig_variogram$exp_var$dist, type="l", lwd=4, ylim=c(0,0.07), col="steelblue3", ylab="semi-varience", xlab="distance")
plot(wTCPDown_variogram$exp_var$gamma~Sig_variogram$exp_var$dist, type="l", lwd=4, ylim=c(0,0.07), col="steelblue3", ylab="semi-varience", xlab="distance")
plot(wTCPUp_variogram$exp_var$gamma~wTCPUp_variogram$exp_var$dist, type="l", lwd=4, ylim=c(0,0.07), col="steelblue3", ylab="semi-varience", xlab="distance")
```

## Compare Spatial Models
```{r}
layout(matrix(c(1,2,3,4,5,6,7,8,9,10), 2, 5, byrow = TRUE))
plot(dat_att$SigStrength, rep(mean(dat_att$SigStrength), nrow(dat_att)), pch=20, xlim=c(-130,-60), ylim=c(-130,-70), xlab="actual SigStrength", ylab="predicted SigStrength", main="Blind Prediction", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$SigStrength, Sig_nearest_predictions, pch=20, xlim=c(-130,-60), ylim=c(-130,-70), xlab="actual SigStrength", ylab="predicted SigStrength", main="Predict Nearest", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$SigStrength, Sig_knn_predictions, pch=20, xlim=c(-130,-60), ylim=c(-130,-70), xlab="actual SigStrength", ylab="predicted SigStrength", main="Regular kNN\nk=7", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$SigStrength, Sig_knn_weighted_predictions, pch=20, xlim=c(-130,-60), ylim=c(-130,-70), xlab="actual SigStrength", ylab="predicted SigStrength", main="Weighted kNN\nk=7", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$SigStrength, Sig_kriging_predictions, pch=20, xlim=c(-130,-50), ylim=c(-130,-70), xlab="actual SigStrength", ylab="predicted SigStrength", main = "Kriging", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
boxplot(abs(mean(dat_att$SigStrength) - dat_att$SigStrength)[dat_att$SigStrength != 0], ylab="absolute prediction error", main="Blind Prediction", ylim=c(0,50))
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
boxplot(abs(Sig_nearest_predictions - dat_att$SigStrength)[dat_att$SigStrength != 0], ylab="absolute prediction error", main="Predict Nearest", ylim=c(0,50))
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
boxplot(abs(Sig_knn_predictions - dat_att$SigStrength)[dat_att$SigStrength != 0], ylab="absolute prediction error", main="Regular kNN", ylim=c(0,50))
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
boxplot(abs(Sig_knn_weighted_predictions - dat_att$SigStrength)[dat_att$SigStrength != 0], ylab="absolute prediction error", main="Weighted kNN", ylim=c(0,50))
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
boxplot(abs(Sig_kriging_predictions - dat_att$SigStrength)[dat_att$SigStrength != 0], ylab="absolute prediction error", main="Kriging", ylim=c(0,50))
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
```

```{r}
layout(matrix(c(1,2,3,4,5,6,7,8,9,10), 2, 5, byrow = TRUE))
plot(dat_att$wMOS, rep(mean(dat_att$wMOS), nrow(dat_att)), pch=20, xlim=c(0,5), ylim=c(0,5), xlab="actual wMOS", ylab="predicted wMOS", main="Blind Prediction", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wMOS, wMOS_nearest_predictions, pch=20, xlim=c(0,5), ylim=c(0,5), xlab="actual wMOS", ylab="predicted wMOS", main="Predict Nearest", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wMOS, wMOS_knn_predictions, pch=20, xlim=c(0,5), ylim=c(0,5), xlab="actual wMOS", ylab="predicted wMOS", main="Regular kNN\nk=7", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wMOS, wMOS_knn_weighted_predictions, pch=20, xlim=c(0,5), ylim=c(0,5), xlab="actual wMOS", ylab="predicted wMOS", main="Weighted kNN\nk=7", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wMOS, wMOS_kriging_predictions, pch=20, xlim=c(0,5), ylim=c(0,5), xlab="actual wMOS", ylab="predicted wMOS", main = "Kriging", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
boxplot(abs(mean(dat_att$wMOS) - dat_att$wMOS), ylab="absolute prediction error", main="Blind Prediction")
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
boxplot(abs(wMOS_nearest_predictions - dat_att$wMOS), ylab="absolute prediction error", main="Predict Nearest")
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
boxplot(abs(wMOS_knn_predictions - dat_att$wMOS), ylab="absolute prediction error", main="Regular kNN")
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
boxplot(abs(wMOS_knn_weighted_predictions - dat_att$wMOS), ylab="absolute prediction error", main="Weighted kNN")
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
boxplot(abs(wMOS_kriging_predictions - dat_att$wMOS), ylab="absolute prediction error", main="Kriging")
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
```

```{r}
layout(matrix(c(1,2,3,4,5,6,7,8,9,10), 2, 5, byrow = TRUE))
plot(dat_att$wTCPDown, rep(mean(dat_att$wTCPDown), nrow(dat_att)), pch=20, xlim=c(0,50000), ylim=c(0,50000), xlab="actual wTCPDown", ylab="predicted wTCPDown", main="Blind Prediction", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wTCPDown, wTCPDown_nearest_predictions, pch=20, xlim=c(0,50000), ylim=c(0,50000), xlab="actual wTCPDown", ylab="predicted wTCPDown", main="Predict Nearest", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wTCPDown, wTCPDown_knn_predictions, pch=20, xlim=c(0,50000), ylim=c(0,50000), xlab="actual wTCPDown", ylab="predicted wTCPDown", main="Regular kNN\nk=7", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wTCPDown, wTCPDown_knn_weighted_predictions, pch=20, xlim=c(0,50000), ylim=c(0,50000), xlab="actual wTCPDown", ylab="predicted wTCPDown", main="Weighted kNN\nk=7", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wTCPDown, wTCPDown_kriging_predictions, pch=20, xlim=c(0,50000), ylim=c(0,50000), xlab="actual wTCPDown", ylab="predicted wTCPDown", main = "Kriging", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
boxplot(abs(mean(dat_att$wTCPDown) - dat_att$wTCPDown), ylab="absolute prediction error", main="Blind Prediction", ylim=c(0,45000))
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown))), lty = 2, col = "red", lwd=3)
boxplot(abs(wTCPDown_nearest_predictions - dat_att$wTCPDown), ylab="absolute prediction error", main="Predict Nearest", ylim=c(0,45000))
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown))), lty = 2, col = "red", lwd=3)
boxplot(abs(wTCPDown_knn_predictions - dat_att$wTCPDown), ylab="absolute prediction error", main="Regular kNN", ylim=c(0,45000))
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown))), lty = 2, col = "red", lwd=3)
boxplot(abs(wTCPDown_knn_weighted_predictions - dat_att$wTCPDown), ylab="absolute prediction error", main="Weighted kNN", ylim=c(0,45000))
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown))), lty = 2, col = "red", lwd=3)
boxplot(abs(wTCPDown_kriging_predictions - dat_att$wTCPDown), ylab="absolute prediction error", main="Kriging", ylim=c(0,45000))
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown))), lty = 2, col = "red", lwd=3)
```

```{r}
layout(matrix(c(1,2,3,4,5,6,7,8,9,10), 2, 5, byrow = TRUE))
plot(dat_att$wTCPUp, rep(mean(dat_att$wTCPUp), nrow(dat_att)), pch=20, xlim=c(0,30000), ylim=c(0,30000), xlab="actual wTCPUp", ylab="predicted wTCPUp", main="Blind Prediction", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wTCPUp, wTCPUp_nearest_predictions, pch=20, xlim=c(0,30000), ylim=c(0,30000), xlab="actual wTCPUp", ylab="predicted wTCPUp", main="Predict Nearest", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wTCPUp, wTCPUp_knn_predictions, pch=20, xlim=c(0,30000), ylim=c(0,30000), xlab="actual wTCPUp", ylab="predicted wTCPUp", main="Regular kNN\nk=7", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wTCPUp, wTCPUp_knn_weighted_predictions, pch=20, xlim=c(0,30000), ylim=c(0,30000), xlab="actual wTCPUp", ylab="predicted wTCPUp", main="Weighted kNN\nk=7", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
plot(dat_att$wTCPUp, wTCPUp_kriging_predictions, pch=20, xlim=c(0,30000), ylim=c(0,30000), xlab="actual wTCPUp", ylab="predicted wTCPUp", main = "Kriging", col=alpha("black",0.25))
abline(0,1, col="red", lwd=3)
boxplot(abs(mean(dat_att$wTCPUp) - dat_att$wTCPUp), ylab="absolute prediction error", main="Blind Prediction", ylim=c(0,25000))
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp))), lty = 2, col = "red", lwd=3)
boxplot(abs(wTCPUp_nearest_predictions - dat_att$wTCPUp), ylab="absolute prediction error", main="Predict Nearest", ylim=c(0,25000))
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp))), lty = 2, col = "red", lwd=3)
boxplot(abs(wTCPUp_knn_predictions - dat_att$wTCPUp), ylab="absolute prediction error", main="Regular kNN", ylim=c(0,25000))
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp))), lty = 2, col = "red", lwd=3)
boxplot(abs(wTCPUp_knn_weighted_predictions - dat_att$wTCPUp), ylab="absolute prediction error", main="Weighted kNN", ylim=c(0,25000))
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp))), lty = 2, col = "red", lwd=3)
boxplot(abs(wTCPUp_kriging_predictions - dat_att$wTCPUp), ylab="absolute prediction error", main="Kriging", ylim=c(0,25000))
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp))), lty = 2, col = "red", lwd=3)
```
