---
title: "CPUC Predicting Mobile Broadband"
author: "Jose Mijangos"
date: "August 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggmap)
library(grid)
library(geosphere)
library(automap)
library(e1071)
```

## Functions
```{r}
# Returns average and reduces NA values
vector_avg = function(x1, x2) {
  x = apply(data.frame(x1,x2), 1, function(x) mean(na.omit(x)))
  x[is.nan(x)] = NA
  return(x)
}
```

## Read Data
```{r}
# Field Test Data
dat_raw = read.csv("C:\\Users\\Josemij39\\Desktop\\CPUC-research\\Round12_Results_2017.csv")
```

## Preprocess Data
```{r collapse=TRUE, warning=FALSE, message=FALSE}
# Convert to Numeric
dat = as.data.frame(apply(dat_raw, 2, as.numeric))

# Restore Factors
dat$Provider = dat_raw$Provider
dat$Network = dat_raw$Network
dat$DeviceType = dat_raw$DeviceType
dat$Type = dat_raw$Type

# Aggregate TCP values
dat$wTCPUp   = vector_avg(dat$wTCPUp1, dat$wTCPUp2)
dat$wTCPDown = vector_avg(dat$wTCPDown1, dat$wTCPDown2)

# Remove tuples with bad lat/long values
dat = dat[dat$Longitude < -100,]

# Project Data
dat = dat[,c("LocationID", "Latitude", "Longitude", "NormalLONG", "NormalLAT", "Provider", "Network", "DeviceType", "Type", "SigStrength", "wMOS", "wTCPDown", "wTCPUp")]

# Remove all NAs
dat = na.omit(dat)

# Select data set for each Provider
dat_att = dat[dat$Provider == "AT&T" & dat$DeviceType=="Phone",]
dat_sprint = dat[dat$Provider == "Sprint" & dat$DeviceType=="Phone",]
dat_tmobile = dat[dat$Provider == "T-Mobile" & dat$DeviceType=="Phone",]
dat_verizon = dat[dat$Provider == "Verizon" & dat$DeviceType=="Phone",]
```

## Plots
```{r}
load("Califonia")

rural = ggmap(map)
rural = rural +   geom_point(data=dat[dat$Type == "Non-Rural",], aes(x=NormalLONG,y=NormalLAT  ), fill="cornflowerblue", pch=21, colour="black", size=1.5)
rural

non_rural = ggmap(map)
non_rural = non_rural + geom_point(data=dat[dat$Type == "Rural",], aes(x=NormalLONG,y=NormalLAT  ), fill="red", pch=21, colour="black", size=1.5)
non_rural

tribal = ggmap(map)
tribal = tribal + geom_point(data=dat[dat$Type == "Tribal",], aes(x=NormalLONG,y=NormalLAT  ), fill="green", pch=21, colour="black", size=1.5)
tribal
```

```{r}
p1 = ggmap(map)
p1 = p1 + 
    geom_point(data=dat_att, aes(x=Longitude,y=Latitude,color=wMOS), size=1.5) +
  scale_colour_gradientn(colors=rainbow(20)[c(14:11,8,6,3:1)])
p1

p2 = ggmap(map)
p2 = p2 + 
  geom_point(data=dat_att[dat_att$SigStrength != 0,], aes(x=Longitude,y=Latitude,color=SigStrength), size=1.5) +
  scale_colour_gradientn(colors=rainbow(20)[c(14:11,8,6,3:1)])
p2

p3 = ggmap(map)
p3 = p3 + 
  geom_point(data=dat_att, aes(x=Longitude,y=Latitude,color=wTCPDown/1000), size=1.5) +
  scale_colour_gradientn(colors=rainbow(20)[c(14:11,8,6,3:1)])
p3

p4 = ggmap(map)
p4 = p4 + 
  geom_point(data=dat_att, aes(x=Longitude,y=Latitude,color=wTCPUp/1000), size=1.5) +
  scale_colour_gradientn(colors=rainbow(20)[c(14:11,8,6,3:1)])
p4
```

## Distance Matrix
```{r}
distance = function(dat_att){
  
earth_radius_in_miles = 3959

n = nrow(dat_att)
locs = as.matrix(dat_att[1:n,c("NormalLONG", "NormalLAT")])
gdist = matrix(rep(NA, n*n), ncol=n)

for (i in 1:n) {
  temp = matrix(as.numeric(rep(locs[i,], each=n)), nrow=n)
  gdist[i,] = distHaversine(temp, locs, r=earth_radius_in_miles)  
}
return(apply(gdist, 1, function(x) sort(x)[2]))
}
```

```{r}
hist(distance(dat_att), breaks = seq(0,100,2), main="Distance to nearest nieghbor\nRural and Urban")
hist(distance(dat_att[dat_att$Type == "Rural",]), breaks = seq(0,100,2), main="Distance to nearest nieghbor\nRural")
hist(distance(dat_att[dat_att$Type == "Non-Rural",]), breaks = seq(0,100,2), main="Distance to nearest nieghbor\nUrban")
```

## kNN Prediction Error
```{r}
prediction_error = function(dat_att){

earth_radius_in_miles = 3959

n = nrow(dat_att)
locs = as.matrix(dat_att[1:n,c("NormalLONG", "NormalLAT")])
gdist = matrix(rep(NA, n*n), ncol=n)

for (i in 1:n) {
  temp = matrix(as.numeric(rep(locs[i,], each=n)), nrow=n)
  gdist[i,] = distHaversine(temp, locs, r=earth_radius_in_miles)  
}

Sig_knn_error = c()
wMOS_knn_error = c()
wTCPDown_knn_error = c()
wTCPUp_knn_error = c()

Sig_weighted_knn_error = c()
wMOS_weighted_knn_error = c()
wTCPDown_weighted_knn_error = c()
wTCPUp_weighted_knn_error = c()

for(l in 1:20) {
  Sig_knn_predictions = c()
  wMOS_knn_predictions = c()
  wTCPDown_knn_predictions = c()
  wTCPUp_knn_predictions = c()

  Sig_knn_weighted_predictions = c()
  wMOS_knn_weighted_predictions = c()
  wTCPDown_knn_weighted_predictions = c()
  wTCPUp_knn_weighted_predictions = c()
  for(i in 1:n) {
    kNearest = order(gdist[i,])[2:l+1]
    weights = 1/sort(gdist[i,][kNearest] + 0.001)
    weights = weights/sum(weights)
    
    Sig_knn_predictions = c(Sig_knn_predictions, mean(dat_att$SigStrength[kNearest]))
    wMOS_knn_predictions = c(wMOS_knn_predictions, mean(dat_att$wMOS[kNearest]))
    wTCPDown_knn_predictions = c(wTCPDown_knn_predictions, mean(dat_att$wTCPDown[kNearest]))
    wTCPUp_knn_predictions = c(wTCPUp_knn_predictions, mean(dat_att$wTCPUp[kNearest]))
    
    Sig_knn_weighted_predictions = c(Sig_knn_weighted_predictions, sum(weights * dat_att$SigStrength[kNearest]))
    wMOS_knn_weighted_predictions = c(wMOS_knn_weighted_predictions, sum(weights * dat_att$wMOS[kNearest]))
    wTCPDown_knn_weighted_predictions = c(wTCPDown_knn_weighted_predictions, sum(weights * dat_att$wTCPDown[kNearest]))
    wTCPUp_knn_weighted_predictions = c(wTCPUp_knn_weighted_predictions, sum(weights * dat_att$wTCPUp[kNearest]))
  }
  Sig_knn_error = c(Sig_knn_error, median(abs(Sig_knn_predictions - dat_att$SigStrength)))
  wMOS_knn_error = c(wMOS_knn_error, median(abs(wMOS_knn_predictions - dat_att$wMOS)))
  wTCPDown_knn_error = c(wTCPDown_knn_error, median(abs(wTCPDown_knn_predictions - dat_att$wTCPDown)/1000))
  wTCPUp_knn_error = c(wTCPUp_knn_error, median(abs(wTCPUp_knn_predictions - dat_att$wTCPUp)/1000))
  
  Sig_weighted_knn_error = c(Sig_weighted_knn_error, median(abs(Sig_knn_weighted_predictions - dat_att$SigStrength)))
  wMOS_weighted_knn_error = c(wMOS_weighted_knn_error, median(abs(wMOS_knn_weighted_predictions - dat_att$wMOS)))
  wTCPDown_weighted_knn_error = c(wTCPDown_weighted_knn_error, median(abs(wTCPDown_knn_weighted_predictions - dat_att$wTCPDown)/1000))
  wTCPUp_weighted_knn_error = c(wTCPUp_weighted_knn_error, median(abs(wTCPUp_knn_weighted_predictions - dat_att$wTCPUp)/1000))
}
return(data.frame(Sig_knn_error, wMOS_knn_error, wTCPDown_knn_error, wTCPUp_knn_error, Sig_weighted_knn_error, wMOS_weighted_knn_error, wTCPDown_weighted_knn_error, wTCPUp_weighted_knn_error))
}
```

```{r}
att = prediction_error(dat_att)
att_rural = prediction_error(dat_att[dat_att$Type == "Rural",])
att_urban = prediction_error(dat_att[dat_att$Type == "Non-Rural",])
```

## kNN Plots
```{r}
layout(matrix(c(1,2,3,4), 2, 2, byrow = TRUE))
plot(att$Sig_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 10), pch=19, ylab="absolute prediction error", main="SigStrength Error")
points(att$Sig_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
grid()

plot(att$wMOS_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 0.1), pch=19, ylab="absolute prediction error", main="wMOS Error")
points(att$wMOS_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
grid()

plot(att$wTCPDown_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 12), pch=19, ylab="absolute prediction error", main="wTCPDown Error")
points(att$wTCPDown_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown)))/1000, lty = 2, col = "red", lwd=3)
grid()

plot(att$wTCPUp_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 6.5), pch=19, ylab="absolute prediction error", main="wTCPUp Error")
points(att$wTCPUp_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp)))/1000, lty = 2, col = "red", lwd=3)
grid()
```

## kNN Rural
```{r}
layout(matrix(c(1,2,3,4), 2, 2, byrow = TRUE))
plot(att_rural$Sig_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 10), pch=19, ylab="absolute prediction error", main="Rural SigStrength Error")
points(att_rural$Sig_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
grid()

plot(att_rural$wMOS_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 0.1), pch=19, ylab="absolute prediction error", main="Rural wMOS Error")
points(att_rural$wMOS_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
grid()

plot(att_rural$wTCPDown_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 12), pch=19, ylab="absolute prediction error", main="Rural wTCPDown Error")
points(att_rural$wTCPDown_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown)))/1000, lty = 2, col = "red", lwd=3)
grid()

plot(att_rural$wTCPUp_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 6.5), pch=19, ylab="absolute prediction error", main="Rural wTCPUp Error")
points(att_rural$wTCPUp_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp)))/1000, lty = 2, col = "red", lwd=3)
grid()
```

## kNN Urban
```{r}
layout(matrix(c(1,2,3,4), 2, 2, byrow = TRUE))
plot(att_urban$Sig_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 10), pch=19, ylab="absolute prediction error", main="Urban SigStrength Error")
points(att_urban$Sig_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$SigStrength - mean(dat_att$SigStrength))), lty = 2, col = "red", lwd=3)
grid()

plot(att_urban$wMOS_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 0.1), pch=19, ylab="absolute prediction error", main="Urban wMOS Error")
points(att_urban$wMOS_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wMOS - mean(dat_att$wMOS))), lty = 2, col = "red", lwd=3)
grid()

plot(att_urban$wTCPDown_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 12), pch=19, ylab="absolute prediction error", main="Urban wTCPDown Error")
points(att_urban$wTCPDown_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wTCPDown - mean(dat_att$wTCPDown)))/1000, lty = 2, col = "red", lwd=3)
grid()

plot(att_urban$wTCPUp_knn_error, type = "b", col="darkorange3", lwd=3, xlab = "k", ylim=c(0, 6.5), pch=19, ylab="absolute prediction error", main="Urban wTCPUp Error")
points(att_urban$wTCPUp_weighted_knn_error, type = "b", col="steelblue2", lwd=3, pch=19)
abline(h = median(abs(dat_att$wTCPUp - mean(dat_att$wTCPUp)))/1000, lty = 2, col = "red", lwd=3)
grid()
```

```{r}
kNN = function(X_test, k, data){
  n = nrow(data)
  locs = as.matrix(data[,c("NormalLONG", "NormalLAT")])
  predicted=c()
  for(i in 1:nrow(X_test)){
    temp = matrix(as.numeric(rep(X_test[i,], each=n)), nrow=n)
    predicted = c(predicted, mean(data$wTCPDown[order(distHaversine(temp, locs, r=earth_radius_in_miles))[1:k]]))
  }

  return(predicted)
}
```

## Heat Maps
```{r collapse=TRUE, warning=FALSE, message=FALSE}
ca=map_data('state', region='California')

ctrl = dat_att

xrang=seq(-124.5,-114,.1)
yrang=seq(32.5,42.25,.1)

xtarg=c()
ytarg=c()

zhat_knn1=matrix(0,length(xrang),length(yrang))
zhat_knn5=matrix(0,length(xrang),length(yrang))
zhat_knn10=matrix(0,length(xrang),length(yrang))

for(j in 1:length(yrang)){
  for(i in 1:length(xrang)){
    if(point.in.polygon(xrang[i], yrang[j], ca$long, ca$lat)){
      xtarg=c(xtarg, xrang[i])
      ytarg=c(ytarg, yrang[j])
    }
    else{
      xtarg=c(xtarg, NA)
      ytarg=c(ytarg, NA)
    }
  }
}

ztarg_knn1 = kNN(data.frame(NormalLONG=xtarg[!is.na(xtarg)], NormalLAT=ytarg[!is.na(ytarg)]), 1, ctrl)
ztarg_knn5 = kNN(data.frame(NormalLONG=xtarg[!is.na(xtarg)], NormalLAT=ytarg[!is.na(ytarg)]), 5, ctrl)
ztarg_knn10 = kNN(data.frame(NormalLONG=xtarg[!is.na(xtarg)], NormalLAT=ytarg[!is.na(ytarg)]), 10, ctrl)

t=0
for(j in 1:length(yrang)){
  for(i in 1:length(xrang)){
    if(point.in.polygon(xrang[i], yrang[j], ca$long, ca$lat)){
      t=t+1
      zhat_knn1[i,j]=ztarg_knn1[t]
      zhat_knn5[i,j]=ztarg_knn5[t]
      zhat_knn10[i,j]=ztarg_knn10[t]
    }
    else{
      zhat_knn1[i,j]=0
      zhat_knn5[i,j]=0
      zhat_knn10[i,j]=0
    }
  }
}
```

```{r collapse=TRUE, warning=FALSE, message=FALSE}
layout(matrix(1:3,ncol=3), width = c(3,3,3),height = c(1,1))

image(xrang, yrang, zhat_knn1, col=rainbow(80)[51:5], xlab="Longitude", ylab="Latitude", main="k Nearest Nieghbor k=1")
lines(ca, lwd=2)

image(xrang, yrang, zhat_knn5, col=rainbow(80)[51:5], xlab="Longitude", ylab="Latitude", main="k Nearest Nieghbor k=5")
lines(ca, lwd=2)

image(xrang, yrang, zhat_knn10, col=rainbow(80)[51:5], xlab="Longitude", ylab="Latitude", main="k Nearest Nieghbor k=10")
lines(ca, lwd=2)
```

## Variograms
```{r collapse=TRUE, warning=FALSE, message=FALSE}
temp = dat_att
coordinates(dat_att) =~ NormalLONG + NormalLAT
Sig_variogram = autofitVariogram(SigStrength/min(SigStrength)~1, dat_att, verbose=FALSE)
wMOS_variogram = autofitVariogram(wMOS/max(wMOS)~1,dat_att, verbose=FALSE)
wTCPDown_variogram = autofitVariogram(wTCPDown/max(wTCPDown)~1,dat_att, verbose=FALSE)
wTCPUp_variogram = autofitVariogram(wTCPUp/max(wTCPUp)~1,dat_att, verbose=FALSE)

layout(matrix(c(1,2,3,4), 2, 2, byrow = TRUE))
plot(Sig_variogram$exp_var$gamma~Sig_variogram$exp_var$dist, type="l", lwd=4, ylim=c(0,0.07), col="steelblue3", ylab="semi-varience", xlab="distance")
plot(wMOS_variogram$exp_var$gamma~Sig_variogram$exp_var$dist, type="l", lwd=4, ylim=c(0,0.07), col="steelblue3", ylab="semi-varience", xlab="distance")
plot(wTCPDown_variogram$exp_var$gamma~Sig_variogram$exp_var$dist, type="l", lwd=4, ylim=c(0,0.07), col="steelblue3", ylab="semi-varience", xlab="distance")
plot(wTCPUp_variogram$exp_var$gamma~wTCPUp_variogram$exp_var$dist, type="l", lwd=4, ylim=c(0,0.07), col="steelblue3", ylab="semi-varience", xlab="distance")
```

### Kriging Maps
```{r collapse=TRUE, warning=FALSE, message=FALSE}
krige_att = autoKrige(wTCPDown/max(wTCPDown) ~ 1, dat_att)
krige_att1 = autoKrige(wTCPDown/max(wTCPDown) ~ 1, dat_att, start_vals = c(NA,12.1,NA))
krige_att2 = autoKrige(wTCPDown/max(wTCPDown) ~ 1, dat_att, start_vals = c(NA,12.2,NA))
```

```{r collapse=TRUE, warning=FALSE, message=FALSE}
krige_att$krige_output@data$var1.pred = krige_att$krige_output@data$var1.pred * max(dat_att$wTCPDown)
plot(krige_att$krige_output, col=rainbow(80)[51:5])
lines(ca, lwd=2)

krige_att1$krige_output@data$var1.pred = krige_att1$krige_output@data$var1.pred * max(dat_att$wTCPDown)
plot(krige_att1$krige_output, col=rainbow(80)[51:5])
lines(ca, lwd=2)

krige_att2$krige_output@data$var1.pred = krige_att2$krige_output@data$var1.pred * max(dat_att$wTCPDown)
plot(krige_att2$krige_output, col=rainbow(80)[51:5])
lines(ca, lwd=2)
```

```{r}
dat_att = temp
sample_error = function(target){
  target = dat_att[,target]
  means = c()
  errors = c()
  for(i in seq(50, nrow(dat_att), 50)+8){
    for(j in 1:1000){
      sam = sample(target, i, replace=FALSE)
      means = c(means, mean(sam))
    }
    errors = c(errors, 2*sd(means))
    means = c()
  }

  return(errors)
}
```

```{r}
par(mar=c(5,5,3,2))
plot(sample_error("wTCPDown")/1000 ~ seq(50, nrow(dat_att), 50), ylim = c(0, 2), xlab="sample size\n(1000 trails per sample size)", main="wTCPDown by sample size", ylab="2 * Standard deviation (Mb/s)", type="b", lwd=2)
abline(h=(1.1*mean(dat_att$wTCPDown) - mean(dat_att$wTCPDown))/1000, col="red", lty=2, lwd=2)
abline(h=(1.05*mean(dat_att$wTCPDown) - mean(dat_att$wTCPDown))/1000, col="orange", lty=2, lwd=2)
abline(h=(1.01*mean(dat_att$wTCPDown) - mean(dat_att$wTCPDown))/1000, col="green", lty=2, lwd=2)
```

```{r}
par(mar=c(5,5,3,2))
plot(sample_error("wTCPUp")/1000 ~ seq(50, nrow(dat_att), 50), ylim = c(0, 1), xlab="sample size\n(1000 trails per sample size)", main="wTCPUp by sample size", ylab="2 * Standard deviation (Mb/s)", type="b", lwd=2)
abline(h=(1.1*mean(dat_att$wTCPUp) - mean(dat_att$wTCPUp))/1000, col="red", lty=2, lwd=2)
abline(h=(1.05*mean(dat_att$wTCPUp) - mean(dat_att$wTCPUp))/1000, col="orange", lty=2, lwd=2)
abline(h=(1.01*mean(dat_att$wTCPUp) - mean(dat_att$wTCPUp))/1000, col="green3", lty=2, lwd=2)
```

```{r}
par(mar=c(5,5,3,2))
plot(sample_error("SigStrength") ~ seq(50, nrow(dat_att), 50), ylim = c(0, 10), xlab="sample size\n(1000 trails per sample size)", main="SigStrength by sample size", ylab="2 * Standard deviation", type="b", lwd=2)
abline(h=0.9*mean(dat_att$SigStrength) - mean(dat_att$SigStrength), col="red", lty=2, lwd=2)
abline(h=0.95*mean(dat_att$SigStrength) - mean(dat_att$SigStrength), col="orange", lty=2, lwd=2)
abline(h=0.99*mean(dat_att$SigStrength) - mean(dat_att$SigStrength), col="green3", lty=2, lwd=2)
```

```{r}
par(mar=c(5,5,3,2))
plot(sample_error("wMOS") ~ seq(50, nrow(dat_att), 50), ylim = c(0, 0.5), xlab="sample size\n(1000 trails per sample size)", main="wMOS by sample size", ylab="2 * Standard deviation", type="b", lwd=2)
abline(h=1.1*mean(dat_att$wMOS) - mean(dat_att$wMOS), col="red", lty=2, lwd=2)
abline(h=1.05*mean(dat_att$wMOS) - mean(dat_att$wMOS), col="orange", lty=2, lwd=2)
abline(h=1.01*mean(dat_att$wMOS) - mean(dat_att$wMOS), col="green3", lty=2, lwd=2)
```